"""first migration

Revision ID: 5b064f583ea4
Revises: 
Create Date: 2023-10-01 12:06:01.896727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b064f583ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id_offer', sa.String(length=255), nullable=False),
    sa.Column('updates', mysql.INTEGER(display_width=5), nullable=True),
    sa.Column('details', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_offer')
    )
    op.create_table('offers_details_raw',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_offer', sa.String(length=255), nullable=False),
    sa.Column('offer_details_raw', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_offer'], ['offers.id_offer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers_raw',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_offer', sa.String(length=255), nullable=False),
    sa.Column('offer_raw', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_offer'], ['offers.id_offer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_raw')
    op.drop_table('offers_details_raw')
    op.drop_table('offers')
    # ### end Alembic commands ###
